"""table table

Revision ID: 242b12d463fd
Revises: 
Create Date: 2020-07-04 12:24:34.408228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242b12d463fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table',
    sa.Column('position', sa.String(length=4), nullable=False),
    sa.Column('content', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('position')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table')
    # ### end Alembic commands ###
